### ISSUE TITLE
Criar parser EstabelecimentoSaudeService

### ISSUE THREAD

**Issue by pedlop** [pedlop/integracao201701#27]
Criar parser do tópico 5.2.1. EstabelecimentoSaudeService, disponível no [Documento CNES](http://datasus.saude.gov.br/images/Interoperabilidade/Especificacao_Tecnica_para_Integracao_com_o_Cadastro_Nacional_de_Estabelecimentos_de_Sade_v1-20.pdf).
Baseando-se:
- No enum já criado do mesmo serviço.
- No arquivo xml do link de homologação do tópico do documento acima, utilizando o SOAPUI.

E criar métodos no arquivo **_Servico.java_**.

**Comment by pedlop** [comment]
@joaoHenrique666 fechar issue após conclusão. 

Sugestão: [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by pedlop** [comment]
@gabrielbo1 fechar issue após conclusão. 

Sugestão: [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by gabrielbo1** [comment]
Seriço terminado junto códigos de teste.

**Comment by gabrielbo1** [comment]
.
