### ISSUE TITLE
Criar métodos 'Operação' para EstabelecimentoSaudeService

### ISSUE THREAD

**Issue by pedlop** [pedlop/integracao201701#7]
@gabrielbo1 
Criar métodos para o EstabelecimentoSaudeService:
- consultarEstabelecimentoSaude
- consultarPreCadastroCNES
- localizarEstabelecimentoSaude

**Comment by pedlop** [comment]
@gabrielbo1 fechar issue após conclusão. 

Sugestão: [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by ronynogueiras** [comment]
Tarefa concluída.

https://github.com/pedlop/integracao201701/commit/752a64d4a5bc217583e856f87b8df4e29c488dcf
